{% set package_name = "typhos" %}
{% set import_name = "typhos" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv



requirements:
  build:
  - python >=3.9
  - pip
  - setuptools_scm
  host:
  - python >=3.9
  - pip
  run:
  - python >=3.9
  - coloredlogs
  - entrypoints
  - numpy
  - numpydoc
  - ophyd >=1.5.0
  - pcdsdevices
  - pcdsutils
  - platformdirs
  - pydm >=1.16.1
  - pyqt
  - pyqtgraph
  - pyyaml
  - qdarkstyle
  - qtawesome
  - qtpy
  - timechart >=1.2.4
  run_constrained:
  - happi >=1.14.0
  - jupyter_client <7.3.2



test:
  commands:
  - typhos --help
  imports:
  - typhos
  - typhos.cli
  requires:
  - caproto
  - doctr
  - doctr-versions-menu
  - flake8
  - ipython>=7.16
  - jinja2<3.1
  - line_profiler <4.0.0
  - pytest
  - pytest-benchmark
  - pytest-qt
  - pytest-timeout
  - simplejson



about:
  dev_url: https://github.com/pcdshub/typhos
  doc_url: https://pcdshub.github.io/typhos
  home: https://github.com/pcdshub/typhos
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE.md
  summary: Automatic-yet-customizable Graphical User Interface Generation for Ophyd
    Devices



extra:
  recipe-maintainers:
  - klauer
  - tangkong
  - zllentz
