{% set data = load_setup_py_data() %}

package:
    name    : typhos
    version : {{ data.get('version') }}

source:
    path: ..

build:
  noarch: python
  entry_points:
    - typhos = typhos.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - coloredlogs
    - entrypoints
    - numpy
    - numpydoc
    - ophyd >=1.5.0
    - pcdsutils
    - pydm >=1.16.1
    - pyqt >=5,<5.15
    - pyqtgraph
    - qdarkstyle
    - qtawesome
    - qtconsole
    - qtpy
    - timechart >=1.2.4
  run_constrained:
    - jupyter_client <7.3.2

about:
  home: https://github.com/pcdshub/typhos
  doc_url: https://pcdshub.github.io/typhos
  dev_url: https://github.com/pcdshub/typhos
  summary: 'Automatic-yet-customizable Graphical User Interface Generation for Ophyd Devices'
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE.md

test:
  imports:
    - typhos
    - typhos.cli
  commands:
    - typhos --help

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka
    - zllentz
